FROM ubeike/raspicat-noetic:amd64-base AS base

SHELL ["/bin/bash", "-c"]
WORKDIR /root/catkin_ws/
RUN source /opt/ros/noetic/setup.bash \ 
  && catkin build

FROM ubeike/raspicat-noetic:arm64v8 AS builder

COPY --from=base /root/catkin_ws/ /root/catkin_ws/

WORKDIR /root/catkin_ws/src/