name: ros-noetic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 22 * * *'

env:
  DOCKER-IMAGE-ENVIRONMENT: ubeike/raspicat-noetic
  DOCKER-CONTEXT: ./
  DOCKER-FILE-ENVIRONMENT: ./.github/Dockerfile.raspicat
  cache-version: v0.0.1

jobs:
  Build-Push:
    runs-on: ubuntu-20.04

    steps:
      - name: Run actions/checkout@v2 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create id_rsa
        run: |
          mkdir -p ./.github/ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ./.github/ssh/id_rsa
      
      - name: Apt install
        run: |
          sudo apt install qemu-user-static

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-ENVIRONMENT }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.DOCKER-IMAGE-ENVIRONMENT }}
          push: true
          cache-from: type=registry,ref==/tmp/.buildx-cache
          cache-to: type=registry,ref==/tmp/.buildx-cache,mode=max