name: ros-noetic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  DOCKER-CONTEXT: ./
  DOCKER-FILE-ARM: ./.github/Dockerfile.raspicat-build

jobs:
  Build-Push:
    runs-on: ubuntu-20.04

    steps:
      - name: Run actions/checkout@v2 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create id_rsa
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e "${{ secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
      
      - name: Apt Snap install
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt install python3-vcstool
          sudo snap install yq

      - name: Sed clone branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          yq -i '.repositories.raspicat.version = "${{ github.head_ref }}"' raspicat_navigation.repos

      - name: Vcs import
        run: |
          mkdir -p repository
          vcs import repository < raspicat_navigation.repos --debug --recursive

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-ARM }}
          builder: ${{ steps.buildx.outputs.name }}
          push: false