name: schedule-build

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 22 * * *'

env:
  DOCKER-IMAGE-BASE-AMD: ubeike/raspicat-noetic:amd64-base
  DOCKER-IMAGE-BASE-ARM: ubeike/raspicat-noetic:arm64v8-base
  DOCKER-IMAGE-ARM: ubeike/raspicat-noetic:arm64v8  
  DOCKER-CONTEXT: ./
  DOCKER-FILE-BASE-AMD: ./.github/Dockerfile.raspicat-amd64-base
  DOCKER-FILE-BASE-ARM: ./.github/Dockerfile.raspicat-arm64v8-base
  DOCKER-FILE-ARM: ./.github/Dockerfile.raspicat-build

jobs:
  Create-Base-Image:
    runs-on: ubuntu-20.04

    steps:
      - name: Run actions/checkout@v2 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create id_rsa
        run: |
          mkdir -p ./.github/ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ./.github/ssh/id_rsa

      - name: Build and push docker image amd64
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-BASE-AMD }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.DOCKER-IMAGE-BASE-AMD }}
          push: true
      
      - name: Apt install
        run: |
          sudo apt install qemu-user-static

      - name: Build and push docker image arm64v8
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-BASE-ARM }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.DOCKER-IMAGE-BASE-ARM }}
          push: true
      
  Build:
    runs-on: ubuntu-20.04
    needs: Create-Base-Image
    steps:
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-ARM }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.DOCKER-IMAGE-ARM }}
          push: true